const quizData = [
    // --- ドメインクイズ (domain) ---
    { tld: ".it", image: "images/domain/domain_Italy.jpg", answer: "イタリア", choices: ["イタリア", "フランス", "スペイン", "ギリシャ"], note: "Italyの略。地中海沿いの街並みが特徴的です。", category: "domain", difficulty_label: "easy" },
    { tld: ".jp", image: "images/domain/domain_Japan.jpg", answer: "日本", choices: ["日本", "韓国", "台湾", "中国"], note: "Japanの略。道路標識や左側通行が大きなヒントです。", category: "domain", difficulty_label: "easy" },
    { tld: ".kr", image: "images/domain/domain_SouthKorea.jpg", answer: "韓国", choices: ["韓国", "日本", "中国", "台湾"], note: "Koreaの略。ハングルの看板で見分けがつきます。", category: "domain", difficulty_label: "easy" },
    { tld: ".mk", image: "images/domain/domain_NorthMacedonia.jpg", answer: "北マケドニア", choices: ["北マケドニア", "ギリシャ", "アルバニア", "ブルガリア"], note: "Macedoniaの略です。", category: "domain", difficulty_label: "hard" },
    { tld: ".mx", image: "images/domain/domain_Mexico.jpg", answer: "メキシコ", choices: ["メキシコ", "スペイン", "コロンビア", "アメリカ"], note: "Mexicoの略。特有の植生や乾燥した風景が特徴です。", category: "domain", difficulty_label: "normal" },
    { tld: ".nz", image: "images/domain/domain_NewZealand.jpg", answer: "ニュージーランド", choices: ["ニュージーランド", "オーストラリア", "イギリス", "カナダ"], note: "New Zealandの略。黄色いセンターラインがないことが多いです。", category: "domain", difficulty_label: "normal" },
    { tld: ".ru", image: "images/domain/domain_Russia.jpg", answer: "ロシア", choices: ["ロシア", "ウクライナ", "ポーランド", "カザフスタン"], note: "Russiaの略。キリル文字の看板が目印です。", category: "domain", difficulty_label: "normal" },
    { tld: ".sg", image: "images/domain/domain_Singapore.jpg", answer: "シンガポール", choices: ["シンガポール", "マレーシア", "香港", "タイ"], note: "Singaporeの略。非常に整備された都市風景が特徴です。", category: "domain", difficulty_label: "easy" },
    { tld: ".tw", image: "images/domain/domain_Taiwan.jpg", answer: "台湾", choices: ["台湾", "中国", "日本", "タイ"], note: "Taiwanの略。繁体字の看板とバイクの多さがヒントです。", category: "domain", difficulty_label: "easy" },
    { tld: ".uk", image: "images/domain/domain_UnitedKingdom.jpg", answer: "イギリス", choices: ["イギリス", "アイルランド", "オーストラリア", "アメリカ"], note: "United Kingdomの略。車のナンバープレート（後部が黄色）が特徴です。", category: "domain", difficulty_label: "normal" },
    { tld: ".vn", image: "images/domain/domain_Vietnam.jpg", answer: "ベトナム", choices: ["ベトナム", "タイ", "カンボジア", "ラオス"], note: "Vietnamの略。独特の形をした家の造りが特徴です。", category: "domain", difficulty_label: "normal" },
    { tld: ".za", image: "images/domain/domain_SouthAfrica.jpg", answer: "南アフリカ", choices: ["南アフリカ", "イギリス", "オーストラリア", "ナイジェリア"], note: "Zuid-Afrika（オランダ語由来）の略。外側が白い道路の区画線が特徴です。", category: "domain", difficulty_label: "normal" },
    { tld: ".ar", image: "images/domain/domain_Argentina.jpg", answer: "アルゼンチン", choices: ["アルゼンチン", "チリ", "ウルグアイ", "スペイン"], note: "Argentinaの略。標識の裏が黒いことが多いです。", category: "domain", difficulty_label: "normal" },
    { tld: ".au", image: "images/domain/domain_Australia.jpg", answer: "オーストラリア", choices: ["オーストラリア", "ニュージーランド", "南アフリカ", "アメリカ"], note: "Australiaの略。非常に長い直線道路やユーカリの木が特徴です。", category: "domain", difficulty_label: "normal" },
    { tld: ".be", image: "images/domain/domain_Belgium.jpg", answer: "ベルギー", choices: ["ベルギー", "フランス", "オランダ", "ドイツ"], note: "Belgiumの略。街灯の形が独特なことが多いです。", category: "domain", difficulty_label: "normal" },
    { tld: ".br", image: "images/domain/domain_Brazil.jpg", answer: "ブラジル", choices: ["ブラジル", "ポルトガル", "アルゼンチン", "コロンビア"], note: "Brazilの略。標識の裏が黒く、背面に「×」の補強があることが特徴です。", category: "domain", difficulty_label: "normal" },
    { tld: ".ca", image: "images/domain/domain_Canada.jpg", answer: "カナダ", choices: ["カナダ", "アメリカ", "イギリス", "フランス"], note: "Canadaの略。アメリカに似ていますが、速度制限がkm/h表記です。", category: "domain", difficulty_label: "normal" },
    { tld: ".ch", image: "images/domain/domain_Switzerland.jpg", answer: "スイス", choices: ["スイス", "ドイツ", "オーストリア", "イタリア"], note: "Confoederatio Helvetica（ラテン語）の略。低い位置にある標識が特徴です。", category: "domain", difficulty_label: "normal" },
    { tld: ".co", image: "images/domain/domain_Colombia.jpg", answer: "コロンビア", choices: ["コロンビア", "ベネズエラ", "メキシコ", "エクアドル"], note: "Colombiaの略。黄色いナンバープレートが大きな目印になります。", category: "domain", difficulty_label: "normal" },
    { tld: ".de", image: "images/domain/domain_Germany.jpg", answer: "ドイツ", choices: ["ドイツ", "オーストリア", "スイス", "オランダ"], note: "Deutschlandの略。プライバシー保護のため、一部地域以外はぼかしが多いです。", category: "domain", difficulty_label: "normal" },
    { tld: ".es", image: "images/domain/domain_Spain.jpg", answer: "スペイン", choices: ["スペイン", "ポルトガル", "イタリア", "メキシコ"], note: "Españaの略。道路脇のガードレールの端が四角い特徴があります。", category: "domain", difficulty_label: "normal" },
    { tld: ".fr", image: "images/domain/domain_France.jpg", answer: "フランス", choices: ["フランス", "スペイン", "イタリア", "ベルギー"], note: "Franceの略。青い縁取りのない町名看板が特徴です。", category: "domain", difficulty_label: "normal" },
    { tld: ".id", image: "images/domain/domain_Indonesia.jpg", answer: "インドネシア", choices: ["インドネシア", "マレーシア", "フィリピン", "タイ"], note: "Indonesiaの略。電柱に黒 and 白の縞模様が塗られていることが多いです。", category: "domain", difficulty_label: "normal" },
    { tld: ".in", image: "images/domain/domain_India.jpg", answer: "インド", choices: ["インド", "パキスタン", "バングラデシュ", "スリランカ"], note: "Indiaの略。独特な言語の看板と、左側通行が特徴です。", category: "domain", difficulty_label: "normal" },
    { tld: ".is", image: "images/domain/domain_Iceland.jpg", answer: "アイスランド", choices: ["アイスランド", "ノルウェー", "アイルランド", "グリーンランド"], note: "Islandの略。木がほとんど生えていない火山岩の風景が特徴です。", category: "domain", difficulty_label: "normal" },


    // --- 文字クイズ (30問) ---
    { id: "text_hangul_Korea_01", image: "images/text/text_hangul_Korea_01.jpg", answer: "韓国", choices: ["韓国", "日本", "中国", "台湾"], note: "丸（○）や直線（ー）の組み合わせが特徴的な**ハングル**です。漢字が混じらず、この独特の形状だけで構成されていれば韓国の可能性が非常に高いです。", category: "text", difficulty_label: "easy" },
    { id: "text_thai_Thailand_01", image: "images/text/text_thai_Thailand_01.jpg", answer: "タイ", choices: ["タイ", "ラオス", "カンボジア", "ミャンマー"], note: "文字の端々に小さな丸（ループ）があり、曲線主体なのが**タイ文字**の特徴です。似ているラオス文字よりも、少し角ばった印象を受けるものが多いです。", category: "text", difficulty_label: "easy" },
    { id: "text_greek_Greece_01", image: "images/text/text_greek_Greece_01.jpg", answer: "ギリシャ", choices: ["ギリシャ", "ロシア", "キプロス", "ブルガリア"], note: "数学の記号で使われる「Σ」「Ω」「Δ」などが看板に見られたら**ギリシャ文字**です。キリル文字と似ていますが、ギリシャ独自の形に注目しましょう。", category: "text", difficulty_label: "normal" },
    { id: "text_latin_Vietnam_01", image: "images/text/text_latin_Vietnam_01.jpg", answer: "ベトナム", choices: ["ベトナム", "タイ", "フィリピン", "インドネシア"], note: "ラテン文字（アルファベット）を使用しますが、**母音の上下に多くの声調記号（アクセントマーク）**がつくのがベトナム語の最大の特徴です。", category: "text", difficulty_label: "normal" },
    { id: "text_latin_Poland_01", image: "images/text/text_latin_Poland_01.jpg", answer: "ポーランド", choices: ["ポーランド", "チェコ", "ハンガリー", "リトアニア"], note: "Lに斜線が入った**「ł」**は、ポーランド語を特定する決定的なヒントになります。他にもzの上に点がある「ż」などもポーランド特有です。", category: "text", difficulty_label: "normal" },
    { id: "text_latin_Iceland_01", image: "images/text/text_latin_Iceland_01.jpg", answer: "アイスランド", choices: ["アイスランド", "ノルウェー", "デンマーク", "フィンランド"], note: "北欧諸国の中でも、**「ð」や「þ」**といった特殊な文字が含まれていればアイスランドで確定です。これらは他の北欧言語には登場しません。", category: "text", difficulty_label: "hard" },
    { id: "text_cyrillic_Ukraine_01", image: "images/text/text_cyrillic_Ukraine_01.jpg", answer: "ウクライナ", choices: ["ロシア", "ウクライナ", "ブルガリア", "モンゴル"], note: "キリル文字の中に、ラテン文字のような**「і」や「ї」**（点付きのi）が混じっていればウクライナです。ロシア語にはこの形の文字はありません。", category: "text", difficulty_label: "hard" },
    { id: "text_latin_Brazil_01", image: "images/text/text_latin_Brazil_01.jpg", answer: "ブラジル", choices: ["ブラジル", "メキシコ", "コロンビア", "スペイン"], note: "南米のスペイン語圏と違いポルトガル語を使います。看板に**「ão」**という綴りがあったり、通りの名が「Rua」で始まっていればブラジルです。", category: "text", difficulty_label: "hard" },
    { id: "text_latin_Indonesia_01", image: "images/text/text_latin_Indonesia_01.jpg", answer: "インドネシア", choices: ["インドネシア", "マレーシア", "フィリピン", "ベトナム"], note: "マレーシアと非常に似ていますが、広告や看板にトップレベルドメインの**「.id」**が見えたらインドネシアと確定できます。", category: "text", difficulty_label: "hard" },
    { id: "text_georgian_Georgia_01", image: "images/text/text_georgian_Georgia_01.jpg", answer: "ジョージア", choices: ["ジョージア", "アルメニア", "ギリシャ", "エチオピア"], note: "スパゲッティのように丸まった、非常に独特な形状の**ジョージア文字**です。他に似た文字がほとんどないため、形を覚えれば即座に判定可能です。", category: "text", difficulty_label: "normal" },
    { id: "text_latin_Romania_01", image: "images/text/text_latin_Romania_01.jpg", answer: "ルーマニア", choices: ["ルーマニア", "イタリア", "ハンガリー", "トルコ"], note: "ラテン文字を使用していますが、『ț』や『ș』といった文字の下にコンマのような記号が付くのがルーマニア語の特徴です。", category: "text", difficulty_label: "normal" },
    { id: "text_latin_Sweden_01", image: "images/text/text_latin_Sweden_01.jpg", answer: "スウェーデン", choices: ["スウェーデン", "アイスランド", "オランダ", "エストニア"], note: "ラテン文字に加え、『å』『ä』『ö』といった北欧特有の記号が付いた文字が看板に見られます。", category: "text", difficulty_label: "easy" },
    { id: "text_latin_Turkey_01", image: "images/text/text_latin_Turkey_01.jpg", answer: "トルコ", choices: ["トルコ", "アゼルバイジャン", "ブルガリア", "ギリシャ"], note: "点のない『ı』や、記号付きの『ğ』『ş』『ç』が特徴。これらが看板にあればトルコの可能性が非常に高いです。", category: "text", difficulty_label: "normal" },
    { id: "text_cyrillic_Bulgaria_01", image: "images/text/text_cyrillic_Bulgaria_01.jpg", answer: "ブルガリア", choices: ["ブルガリア", "ロシア", "北マケドニア", "セルビア"], note: "キリル文字を使用。ブルガリア語は『ъ』（硬音記号）を多用するため、看板の中にこの文字を探すのがポイントです。", category: "text", difficulty_label: "hard" },
    { id: "text_cyrillic_Serbia_01", image: "images/text/text_cyrillic_Serbia_01.jpg", answer: "セルビア", choices: ["セルビア", "ブルガリア", "モンテネグロ", "ギリシャ"], note: "キリル文字ですが、セルビア語特有の『ђ』や『љ』『њ』といった独自の字形が含まれるのが識別点です。", category: "text", difficulty_label: "hard" },
    { id: "text_khmer_Cambodia_01", image: "images/text/text_khmer_Cambodia_01.jpg", answer: "カンボジア", choices: ["カンボジア", "タイ", "ラオス", "ミャンマー"], note: "クメール文字は、タイ文字よりも曲線が複雑で、文字の上部に装飾的な飾りが付いているものが多いのが特徴です。", category: "text", difficulty_label: "hard" },
    { id: "text_lao_Laos_01", image: "images/text/text_lao_Laos_01.jpg", answer: "ラオス", choices: ["ラオス", "タイ", "カンボジア", "ベトナム"], note: "タイ文字に非常に似ていますが、タイ文字よりも全体的に丸っこく、角が取れたような形をしています。", category: "text", difficulty_label: "hard" },
    { id: "text_dzongkha_Bhutan_01", image: "images/text/text_dzongkha_Bhutan_01.jpg", answer: "ブータン", choices: ["ブータン", "ネパール", "インド", "チベット"], note: "ゾンカ文字です。文字の上部に水平な直線（頭線）があり、そこから文字がぶら下がっているような形をしています。", category: "text", difficulty_label: "hard" },
    { id: "text_georgian_Georgia_01", image: "images/text/text_georgian_Georgia_01.jpg", answer: "ジョージア", choices: ["ジョージア", "アルメニア", "ギリシャ", "タイ"], note: "スパゲッティのように丸まった、曲線主体の独特な形状を持つジョージア文字（ムヘドルリ）が特徴です。", category: "text", difficulty_label: "normal" },
    { id: "text_armenian_Armenia_01", image: "images/text/text_armenian_Armenia_01.jpg", answer: "アルメニア", choices: ["アルメニア", "ジョージア", "エチオピア", "ギリシャ"], note: "ジョージア文字に似ていますが、ジョージア文字よりも直線的で角ばった字形がアルメニア文字の特徴です。", category: "text", difficulty_label: "hard" },
    { id: "text_burmese_Myanmar_01", image: "images/text/text_burmese_Myanmar_01.jpg", answer: "ミャンマー", choices: ["ミャンマー", "タイ", "ラオス", "カンボジア"], note: "円形や半円の組み合わせで構成される非常に丸っこいビルマ文字が最大の特徴です。", category: "text", difficulty_label: "normal" },
    { id: "text_amharic_Ethiopia_01", image: "images/text/text_amharic_Ethiopia_01.jpg", answer: "エチオピア", choices: ["エチオピア", "イスラエル", "アルメニア", "タイ"], note: "縦棒や点、小さな丸を組み合わせたような独特の形状を持つゲエズ文字（アムハラ文字）です。", category: "text", difficulty_label: "hard" },
    { id: "text_latin_Denmark_01", image: "images/text/text_latin_Denmark_01.jpg", answer: "デンマーク", choices: ["デンマーク", "スウェーデン", "フィンランド", "オランダ"], note: "『ø』や『æ』といった文字が含まれていれば、デンマークかノルウェーの可能性が非常に高いです。", category: "text", difficulty_label: "normal" },
    { id: "text_latin_Estonia_01", image: "images/text/text_latin_Estonia_01.jpg", answer: "エストニア", choices: ["エストニア", "フィンランド", "ラトビア", "リトアニア"], note: "フィンランド語に非常に似ていますが、波打つ記号が付いた『õ』があればエストニア確定です。", category: "text", difficulty_label: "hard" },
    { id: "text_hindi_India_01", image: "images/text/text_hindi_India_01.jpg", answer: "インド", choices: ["インド", "ネパール", "バングラデシュ", "タイ"], note: "文字の上部に一本の長い横棒（シロレーカー）が通っているのがヒンディー語の特徴です。", category: "text", difficulty_label: "easy" },
    { id: "text_arabic_UAE_01", image: "images/text/text_arabic_UAE_01.jpg", answer: "アラブ首長国連邦", choices: ["アラブ首長国連邦", "サウジアラビア", "ヨルダン", "エジプト"], note: "アラビア文字に加え、豪華な近代建築や高層ビルが並ぶ都市景観が特徴です。", category: "text", difficulty_label: "normal" },
    { id: "text_meta_Austria_01", image: "images/text/text_meta_Austria_01.jpg", answer: "オーストリア", choices: ["オーストリア", "ドイツ", "スイス", "ベルギー"], note: "ドイツ語（ラテン文字）の看板ですが、末尾に『.at』ドメインがあれば、オーストリアであると確定できます。", category: "text", difficulty_label: "hard" },
    { id: "text_meta_SouthAfrica_01", image: "images/text/text_meta_SouthAfrica_01.jpg", answer: "南アフリカ", choices: ["南アフリカ", "オーストラリア", "イギリス", "ケニア"], note: "英語の看板が並びますが、ドメインの『.za』は南アフリカ固有のメタ情報です。", category: "text", difficulty_label: "normal" },
    { id: "text_meta_France_01", image: "images/text/text_meta_France_01.jpg", answer: "フランス", choices: ["フランス", "カナダ", "ベルギー", "イタリア"], note: "フランスの都市部でよく見られる、建物の角に取り付けられた青い住所看板です。『Rue（通り）』という表記が特徴です。", category: "text", difficulty_label: "easy" },
    { id: "text_meta_Mexico_01", image: "images/text/text_meta_Mexico_01.jpg", answer: "メキシコ", choices: ["メキシコ", "スペイン", "コロンビア", "アルゼンチン"], note: "スペイン語の『Calle（通り）』という表記に加え、メキシコ特有の白地に黒文字、あるいは街区番号（Colonia）が記載された看板が特徴です。", category: "text", difficulty_label: "normal" },


    // --- 標識：横断歩道 (sign-crossing) 完全修正版 ---
    { image: "images/sign/crossing/sign_crossing_Ireland.jpg", answer: "アイルランド", choices: ["アイルランド", "イギリス", "フランス", "アイスランド"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Israel.jpg", answer: "イスラエル", choices: ["イスラエル", "ヨルダン", "ギリシャ", "エジプト"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Italy.jpg", answer: "イタリア", choices: ["イタリア", "フランス", "スペイン", "ギリシャ"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Jamaica.jpg", answer: "ジャマイカ", choices: ["ジャマイカ", "キューバ", "バハマ", "メキシコ"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Kosovo.jpg", answer: "コソボ", choices: ["コソボ", "アルバニア", "セルビア", "北マケドニア"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Kuwait.jpg", answer: "クウェート", choices: ["クウェート", "カタール", "サウジアラビア", "UAE"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Latvia.jpg", answer: "ラトビア", choices: ["ラトビア", "エストニア", "リトアニア", "ロシア"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Luxembourg.jpg", answer: "ルクセンブルク", choices: ["ルクセンブルク", "ベルギー", "フランス", "ドイツ"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Mexico.jpg", answer: "メキシコ", choices: ["メキシコ", "アメリカ", "コロンビア", "スペイン"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_MK.jpg", answer: "北マケドニア", choices: ["北マケドニア", "ギリシャ", "ブルガリア", "セルビア"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Mongolia.jpg", answer: "モンゴル", choices: ["モンゴル", "中国", "ロシア", "カザフスタン"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Nepal.jpg", answer: "ネパール", choices: ["ネパール", "インド", "ブータン", "パキスタン"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Netherlands.jpg", answer: "オランダ", choices: ["オランダ", "ベルギー", "ドイツ", "デンマーク"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Norway.jpg", answer: "ノルウェー", choices: ["ノルウェー", "スウェーデン", "デンマーク", "フィンランド"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Oman.jpg", answer: "オマーン", choices: ["オマーン", "UAE", "サウジアラビア", "イエメン"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Pakistan.jpg", answer: "パキスタン", choices: ["パキスタン", "インド", "イラン", "アフガニスタン"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Philippines.jpg", answer: "フィリピン", choices: ["フィリピン", "インドネシア", "マレーシア", "ベトナム"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Poland.jpg", answer: "ポーランド", choices: ["ポーランド", "ドイツ", "チェコ", "ウクライナ"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Portugal.jpg", answer: "ポルトガル", choices: ["ポルトガル", "スペイン", "フランス", "イタリア"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Qatar.jpg", answer: "カタール", choices: ["カタール", "UAE", "クウェート", "バーレーン"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Slovakia.jpg", answer: "スロバキア", choices: ["スロバキア", "チェコ", "ハンガリー", "オーストリア"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Slovenia.jpg", answer: "スロベニア", choices: ["スロベニア", "イタリア", "クロアチア", "オーストリア"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_SouthAfrica.jpg", answer: "南アフリカ", choices: ["南アフリカ", "ナミビア", "ボツワナ", "ジンバブエ"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Spain.jpg", answer: "スペイン", choices: ["スペイン", "ポルトガル", "フランス", "モロッコ"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Sweden.jpg", answer: "スウェーデン", choices: ["スウェーデン", "ノルウェー", "フィンランド", "デンマーク"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Switzerland.jpg", answer: "スイス", choices: ["スイス", "ドイツ", "フランス", "イタリア"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Thailand.jpg", answer: "タイ", choices: ["タイ", "ラオス", "カンボジア", "マレーシア"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_UAE.jpg", answer: "アラブ首長国連邦", choices: ["アラブ首長国連邦", "オマーン", "サウジアラビア", "カタール"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Uganda.jpg", answer: "ウガンダ", choices: ["ウガンダ", "ケニア", "ルワンダ", "タンザニア"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_UnitedKingdom.jpg", answer: "イギリス", choices: ["イギリス", "アイルランド", "オーストラリア", "アメリカ"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Ukraine.jpg", answer: "ウクライナ", choices: ["ウクライナ", "ロシア", "ポーランド", "ベラルーシ"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Venezuela.jpg", answer: "ベネズエラ", choices: ["ベネズエラ", "コロンビア", "ブラジル", "ガイアナ"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Vietnam.jpg", answer: "ベトナム", choices: ["ベトナム", "中国", "ラオス", "カンボジア"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Albania.jpg", answer: "アルバニア", choices: ["アルバニア", "ギリシャ", "コソボ", "イタリア"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Argentina.jpg", answer: "アルゼンチン", choices: ["アルゼンチン", "チリ", "ウルグアイ", "ブラジル"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Bangladesh.jpg", answer: "バングラデシュ", choices: ["バングラデシュ", "インド", "ミャンマー", "ネパール"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Brazil.jpg", answer: "ブラジル", choices: ["ブラジル", "アルゼンチン", "コロンビア", "パラグアイ"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Cambodia.jpg", answer: "カンボジア", choices: ["カンボジア", "タイ", "ベトナム", "ラオス"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Chile.jpg", answer: "チリ", choices: ["チリ", "アルゼンチン", "ブラジル", "コロンビア"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Croatia.jpg", answer: "クロアチア", choices: ["クロアチア", "スロベニア", "セルビア", "イタリア"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Cyprus.jpg", answer: "キプロス", choices: ["キプロス", "ギリシャ", "トルコ", "エジプト"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Czechia.jpg", answer: "チェコ", choices: ["チェコ", "スロバキア", "ドイツ", "ポーランド"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Egypt.jpg", answer: "エジプト", choices: ["エジプト", "ヨルダン", "サウジアラビア", "リビア"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Estonia.jpg", answer: "エストニア", choices: ["エストニア", "ラトビア", "リトアニア", "ロシア"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Finland.jpg", answer: "フィンランド", choices: ["フィンランド", "スウェーデン", "エストニア", "ノルウェー"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_France.jpg", answer: "フランス", choices: ["フランス", "スペイン", "イタリア", "ベルギー"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Germany.jpg", answer: "ドイツ", choices: ["ドイツ", "オーストリア", "チェコ", "オランダ"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Hungary.jpg", answer: "ハンガリー", choices: ["ハンガリー", "ルーマニア", "スロバキア", "オーストリア"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_India.jpg", answer: "インド", choices: ["インド", "パキスタン", "バングラデシュ", "スリランカ"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Indonesia.jpg", answer: "インドネシア", choices: ["インドネシア", "マレーシア", "フィリピン", "タイ"], note: "", category: "sign-crossing", difficulty_label: "normal" },
    { image: "images/sign/crossing/sign_crossing_Iran.jpg", answer: "イラン", choices: ["イラン", "イラク", "トルコ", "パキスタン"], note: "", category: "sign-crossing", difficulty_label: "normal" },

    // --- 標識：一時停止 (sign-stop) ---
    { image: "images/sign/stop/sign_stop_Denmark.jpg", answer: "デンマーク", choices: ["デンマーク", "ノルウェー", "スウェーデン", "ドイツ"], note: "デンマークの一時停止標識です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Egypt.jpg", answer: "エジプト", choices: ["エジプト", "サウジアラビア", "ヨルダン", "モロッコ"], note: "アラビア語で「قف（キフ）」と書かれています。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Estonia.jpg", answer: "エストニア", choices: ["エストニア", "ラトビア", "リトアニア", "フィンランド"], note: "エストニアの一時停止標識です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Ethiopia.jpg", answer: "エチオピア", choices: ["エチオピア", "ケニア", "タイ", "ラオス"], note: "アムハラ語が特徴的なエチオピアの標識です。", category: "sign-stop", difficulty_label: "hard" },
    { image: "images/sign/stop/sign_stop_Finland.jpg", answer: "フィンランド", choices: ["フィンランド", "スウェーデン", "エストニア", "ノルウェー"], note: "フィンランドの一時停止標識です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Hongkong.jpg", answer: "香港", choices: ["香港", "中国", "台湾", "シンガポール"], note: "「停 STOP」のように英語と漢字が併記されています。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Hungary.jpg", answer: "ハンガリー", choices: ["ハンガリー", "ルーマニア", "スロバキア", "オーストリア"], note: "ハンガリーの一時停止標識です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Iceland.jpg", answer: "アイスランド", choices: ["アイスランド", "アイルランド", "デンマーク", "ノルウェー"], note: "アイスランドの一時停止標識です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Indiabengali.jpg", answer: "インド", choices: ["インド", "バングラデシュ", "パキスタン", "スリランカ"], note: "ベンガル文字が併記されているインドの標識です。", category: "sign-stop", difficulty_label: "hard" },
    { image: "images/sign/stop/sign_stop_Indian.jpg", answer: "インド", choices: ["インド", "パキスタン", "ネパール", "スリランカ"], note: "ヒンディー語併記のインドの標識です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Indonesia.jpg", answer: "インドネシア", choices: ["インドネシア", "マレーシア", "フィリピン", "ベトナム"], note: "インドネシアの一時停止標識です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Ireland.jpg", answer: "アイルランド", choices: ["アイルランド", "イギリス", "フランス", "アメリカ"], note: "アイルランドの一時停止標識です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Israel.jpg", answer: "イスラエル", choices: ["イスラエル", "ヨルダン", "ギリシャ", "エジプト"], note: "手のひらのマークが描かれています。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Jamaica.jpg", answer: "ジャマイカ", choices: ["ジャマイカ", "キューバ", "バハマ", "メキシコ"], note: "ジャマイカの一時停止標識です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Japan.jpg", answer: "日本", choices: ["日本", "韓国", "中国", "台湾"], note: "世界でも珍しい逆三角形の標識です。", category: "sign-stop", difficulty_label: "easy" },
    { image: "images/sign/stop/sign_stop_Laos.jpg", answer: "ラオス", choices: ["ラオス", "タイ", "カンボジア", "ベトナム"], note: "ラオス文字が使われています。", category: "sign-stop", difficulty_label: "hard" },
    { image: "images/sign/stop/sign_stop_Libya.jpg", answer: "リビア", choices: ["リビア", "エジプト", "チュニジア", "モロッコ"], note: "アラビア語のみの表記が特徴です。", category: "sign-stop", difficulty_label: "hard" },
    { image: "images/sign/stop/sign_stop_Malaysia.jpg", answer: "マレーシア", choices: ["マレーシア", "インドネシア", "タイ", "フィリピン"], note: "「BERHENTI」はマレー語で止まれを意味します。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Malaysia2.jpg", answer: "マレーシア", choices: ["マレーシア", "インドネシア", "シンガポール", "ブルネイ"], note: "別パターンのマレーシア標識です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Mexico.jpg", answer: "メキシコ", choices: ["メキシコ", "スペイン", "アルゼンチン", "コロンビア"], note: "スペイン語の「ALTO」が使われています。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Mongol.jpg", answer: "モンゴル", choices: ["モンゴル", "ロシア", "中国", "カザフスタン"], note: "キリル文字で「ЗОГС」と書かれています。", category: "sign-stop", difficulty_label: "hard" },
    { image: "images/sign/stop/sign_stop_Nigeria.jpg", answer: "ナイジェリア", choices: ["ナイジェリア", "ガーナ", "ケニア", "南アフリカ"], note: "ナイジェリアの一時停止標識です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Norwegian.jpg", answer: "ノルウェー", choices: ["ノルウェー", "スウェーデン", "デンマーク", "フィンランド"], note: "ノルウェーの一時停止標識です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Oman.jpg", answer: "オマーン", choices: ["オマーン", "UAE", "カタール", "サウジアラビア"], note: "英語とアラビア語が併記されています。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Peru.jpg", answer: "ペルー", choices: ["ペルー", "コロンビア", "メキシコ", "チリ"], note: "スペイン語の「PARE」です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Philippines.jpg", answer: "フィリピン", choices: ["フィリピン", "インドネシア", "ベトナム", "マレーシア"], note: "フィリピンの一時停止標識です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Puertorico.jpg", answer: "プエルトリコ", choices: ["プエルトリコ", "メキシコ", "スペイン", "アメリカ"], note: "アメリカ領ですがスペイン語の「PARE」を使います。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Saudiarabia.jpg", answer: "サウジアラビア", choices: ["サウジアラビア", "エジプト", "オマーン", "UAE"], note: "英語とアラビア語が併記されています。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Slovenia.jpg", answer: "スロベニア", choices: ["スロベニア", "イタリア", "クロアチア", "オーストリア"], note: "スロベニアの一時停止標識です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Spain.jpg", answer: "スペイン", choices: ["スペイン", "ポルトガル", "フランス", "メキシコ"], note: "スペインは「PARE」ではなく英語の「STOP」を使う地域があります。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Sweden.jpg", answer: "スウェーデン", choices: ["スウェーデン", "ノルウェー", "フィンランド", "デンマーク"], note: "スウェーデンの一時停止標識です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Thailand.jpg", answer: "タイ", choices: ["タイ", "ラオス", "カンボジア", "ベトナム"], note: "タイ文字で「หยุด」と書かれています。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Tunisia.jpg", answer: "チュニジア", choices: ["チュニジア", "リビア", "モロッコ", "フランス"], note: "アラビア語とフランス語の併記が一般的です。", category: "sign-stop", difficulty_label: "hard" },
    { image: "images/sign/stop/sign_stop_Uganda.jpg", answer: "ウガンダ", choices: ["ウガンダ", "ケニア", "ルワンダ", "エチオピア"], note: "ウガンダの一時停止標識です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Ukraine.jpg", answer: "ウクライナ", choices: ["ウクライナ", "ロシア", "ポーランド", "ベラルーシ"], note: "キリル文字ではなく「STOP」を使うことが増えています。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Venezuela.jpg", answer: "ベネズエラ", choices: ["ベネズエラ", "コロンビア", "ペルー", "ブラジル"], note: "スペイン語の「PARE」です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Argentina.jpg", answer: "アルゼンチン", choices: ["アルゼンチン", "チリ", "ウルグアイ", "スペイン"], note: "スペイン語の「PARE」です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Australia.jpg", answer: "オーストラリア", choices: ["オーストラリア", "ニュージーランド", "イギリス", "アメリカ"], note: "オーストラリアの一時停止標識です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Bhutan.jpg", answer: "ブータン", choices: ["ブータン", "ネパール", "インド", "チベット"], note: "ゾンカ文字が特徴的です。", category: "sign-stop", difficulty_label: "hard" },
    { image: "images/sign/stop/sign_stop_Brazil.jpg", answer: "ブラジル", choices: ["ブラジル", "ポルトガル", "アルゼンチン", "メキシコ"], note: "ポルトガル語の「PARE」です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Brunei.jpg", answer: "ブルネイ", choices: ["ブルネイ", "マレーシア", "インドネシア", "タイ"], note: "ジャウィ文字併記のマレー語が特徴です。", category: "sign-stop", difficulty_label: "hard" },
    { image: "images/sign/stop/sign_stop_Cambodia.jpg", answer: "カンボジア", choices: ["カンボジア", "ラオス", "ベトナム", "タイ"], note: "クメール文字が使われています。", category: "sign-stop", difficulty_label: "hard" },
    { image: "images/sign/stop/sign_stop_Canada.jpg", answer: "カナダ", choices: ["カナダ", "アメリカ", "フランス", "イギリス"], note: "ケベック州以外では「STOP」が一般的です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Canadaquebec.jpg", answer: "カナダ", choices: ["カナダ", "フランス", "ベルギー", "スイス"], note: "ケベック州ではフランス語の「ARRÊT」が使われます。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_Chile.jpg", answer: "チリ", choices: ["チリ", "アルゼンチン", "ペルー", "スペイン"], note: "スペイン語の「PARE」です。", category: "sign-stop", difficulty_label: "normal" },
    { image: "images/sign/stop/sign_stop_China.jpg", answer: "中国", choices: ["中国", "台湾", "日本", "香港"], note: "漢字で「停」と書かれています。", category: "sign-stop", difficulty_label: "easy" },
    { image: "images/sign/stop/sign_stop_Colombia.jpg", answer: "コロンビア", choices: ["コロンビア", "ベネズエラ", "メキシコ", "エクアドル"], note: "スペイン語の「PARE」です。", category: "sign-stop", difficulty_label: "normal" }
];